#ifndef _APS_CXX_AUDIO_DETECT_CLASS_H_
#define _APS_CXX_AUDIO_DETECT_CLASS_H_

#define _POSIX
#define USE_MEMMGR_FENCE
#define ATTENTION_USE_FILENAME_LINE

#endif /* _APS_CXX_AUDIO_DETECT_CLASS_H_ */