# Application makefile

# Command name (Public function 'int <APPNAME>_main(void)' required)
APPNAME =

# Application execute priority (Range: 0 ~ 255, Default: 100)
PRIORITY =

# Application stack memory size (Default: 2048)
STACKSIZE =

# Main source code
MAINSRC = aps_cxx_audio_detect_main.c

# Additional C source files (*.c)
CSRCS =

# Additional C++ source files (*.cxx)
CXXSRCS = 
#CXXSRCS += aps_cxx_audio_detect_class.cxx
#CXXSRCS += worker_ctrl.cxx

# Additional assembler source files (*.S)
ASRCS =

# C compiler flags
CFLAGS =

# C++ compiler flags
CXXFLAGS =

include $(APPDIR)/.vscode/application.mk
